---
  - name: Install Git
    apt:
      pkg: git
      state: installed
      update_cache: yes

  - name: Download repository with swarm script
    git:
      repo: https://github.com/rcbops-qe/jenkins-oa.git
      version: master
      dest: /root/jenkins-oa
      force: yes

  - name: Run setup slave script
    environment:
      JENKINS_SLAVE: "{{ slave_name }}"
      JENKINS_USERNAME: "{{ github_username }}"
      JENKINS_TOKEN: "{{ github_token }}"
    shell: ./scripts/jenkins-slave/setup.sh
    args:
        executable: /bin/bash
        chdir: /root/jenkins-oa/
    register: result

  - name: Readable output of setup slave script
    debug: var=result.stdout.split('\n')

