---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Provision a set of instances
    local_action:
        module: rax
        name: "{{ name }}"
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        count: "{{ count }}"
        key_name: "{{ key_name }}"
        group: "{{ group }}"
        wait: yes
    register: rax
