---
- hosts: localhost
  connection: local
  gather_facts: False
  tags:
    - build
  roles:
    - build_instances

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - get_instance_by_name

- hosts: cloud_instances
  roles:
    - run_scripts
