---
- hosts: localhost
  connection: local
  gather_facts: False
  tags:
    - build
  roles:
    - build_instances

- hosts: localhost
  connection: local
  gather_facts: False
  tags:
    - always
  roles:
    - get_instance_by_name

- hosts: cloud_instances
  roles:
    - { role: clone_setup_scripts,  tags: [ 'always' ] }
    - { role: setup_host,  tags: [ 'host' ] }
    - { role: setup_cobbler,  tags: [ 'cobbler' ] }
    - { role: setup_virsh_net,  tags: [ 'networks' ] }
    - { role: deploy_vms,  tags: [ 'vms' ] }
    - { role: deploy_osa_setup,  tags: [ 'osa' ] }
