---
  - name: Runs the deploy-osa script without the run OpenStack Ansible step
    shell: RUN_OSA=false && OSA_BRANCH={{ osa_branch }} && source deploy-osa.sh
    args:
        executable: /bin/bash
        chdir: /root/openstack-ansible-ops/multi-node-aio
    register: result

  - name: Readable output of deploy-osa script
    debug: var=result.stdout.split('\n')
