---
  - name: Install Git
    apt:
      pkg: git
      state: installed
      update_cache: no

  - name: Download repository with setup scripts
    git:
      repo: https://github.com/rcbops-qe/openstack-ansible-ops.git
      version: master
      dest: /root/openstack-ansible-ops
      force: yes
