---
  - name: Run setup host script
    shell: PARTITION_HOST=true && source setup-host.sh
    args:
        executable: /bin/bash
        chdir: /root/openstack-ansible-ops/multi-node-aio
    register: result

  - name: Readable output of setup host script
    debug: var=result.stdout.split('\n')

  - name: Run setup cobbler script
    shell: SSHKEY=$(cat /root/.ssh/id_rsa.pub) && source setup-cobbler.sh
    args:
        executable: /bin/bash
        chdir: /root/openstack-ansible-ops/multi-node-aio
    register: result

  - name: Readable output of setup cobbler script
    debug: var=result.stdout.split('\n')

  - name: Run setup virsh net script
    command: source setup-virsh-net.sh
    args:
        executable: /bin/bash
        chdir: /root/openstack-ansible-ops/multi-node-aio
    register: result

  - name: Readable output of virsh net setup script
    debug: var=result.stdout.split('\n')

  - name: Run deploy vms script
    command: source deploy-vms.sh
    args:
        executable: /bin/bash
        chdir: /root/openstack-ansible-ops/multi-node-aio
    register: result

  - name: Readable output of deploy vms script
    debug: var=result.stdout.split('\n')
