---
  - name: Run setup host script
    shell: PARTITION_HOST=true && source setup-host.sh
    args:
        executable: /bin/bash
        chdir: /root/openstack-ansible-ops/multi-node-aio
    register: result

  - name: Readable output of setup host script
    debug: var=result.stdout.split('\n')
